on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *' # every month

jobs:
  build:
    runs-on: ubuntu-latest
    name: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - run: Rscript -e 'print("hello")'

      - name: Install pak
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/devel/")
        shell: Rscript {0}

      - name: install sf
        run: |
          pak::local_system_requirements("ubuntu", "20.04", execute = TRUE, sudo = TRUE, echo = TRUE)
          install.packages("sf")
          library(sf)
          nc <- st_read(system.file("shape/nc.shp", package="sf"))
          class(nc)
        shell: Rscript {0}
